version: '3.9'

services:
  app:
    image: python:3.8
    container_name: weather_app_test
    working_dir: /app
    volumes:
      - .:/app # Mount the current directory to /app in the container
    command: bash bin/tests.sh
    environment:
      - PYTHONPATH=/app
